--
-- PostgreSQL database dump
--

\restrict Eq1s4xQ3V7s4i8S35waQsy2Hz2AALCYFitCGck78bRFUX9rph0mJM1LLydYoHfY

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: maintenance_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maintenance_items (
    id bigint NOT NULL,
    active boolean NOT NULL,
    description character varying(500),
    estimated_price bigint,
    name character varying(50) NOT NULL
);


--
-- Name: maintenance_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.maintenance_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.members (
    id bigint NOT NULL,
    active boolean NOT NULL,
    email character varying(100) NOT NULL,
    name character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT members_role_check CHECK (((role)::text = ANY ((ARRAY['MEMBER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation_items (
    id bigint NOT NULL,
    maintenance_item_id bigint NOT NULL,
    reservation_id bigint NOT NULL
);


--
-- Name: reservation_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservation_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations (
    id bigint NOT NULL,
    reservation_date date NOT NULL,
    reservation_time time(0) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    member_id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    CONSTRAINT reservations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: reservations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles (
    id bigint NOT NULL,
    manufacturer character varying(50),
    model character varying(100) NOT NULL,
    model_year integer,
    vehicle_number character varying(20) NOT NULL,
    member_id bigint NOT NULL
);


--
-- Name: vehicles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_items maintenance_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_items
    ADD CONSTRAINT maintenance_items_pkey PRIMARY KEY (id);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- Name: reservation_items reservation_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_items
    ADD CONSTRAINT reservation_items_pkey PRIMARY KEY (id);


--
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);


--
-- Name: maintenance_items uk_maintenance_item_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_items
    ADD CONSTRAINT uk_maintenance_item_name UNIQUE (name);


--
-- Name: members uk_member_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT uk_member_email UNIQUE (email);


--
-- Name: reservation_items uk_reservation_maintenance_item; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_items
    ADD CONSTRAINT uk_reservation_maintenance_item UNIQUE (reservation_id, maintenance_item_id);


--
-- Name: vehicles uk_vehicle_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT uk_vehicle_number UNIQUE (vehicle_number);


--
-- Name: vehicles vehicles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);


--
-- Name: idx_reservation_member_date_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservation_member_date_time ON public.reservations USING btree (member_id, reservation_date, reservation_time);


--
-- Name: reservation_items fk2ap3rkfd3hwifimki537cw6pn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_items
    ADD CONSTRAINT fk2ap3rkfd3hwifimki537cw6pn FOREIGN KEY (maintenance_item_id) REFERENCES public.maintenance_items(id);


--
-- Name: reservations fk7s1rlt0ccv2hjeaubf52di8er; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk7s1rlt0ccv2hjeaubf52di8er FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);


--
-- Name: reservation_items fkahatpyi4mk3o5dcqt7d51r31k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_items
    ADD CONSTRAINT fkahatpyi4mk3o5dcqt7d51r31k FOREIGN KEY (reservation_id) REFERENCES public.reservations(id);


--
-- Name: reservations fki17vaaphgbnwr0tbrg0qu0q66; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fki17vaaphgbnwr0tbrg0qu0q66 FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: vehicles fkp05vr1t3yu9egn5t8fsmsp0k4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT fkp05vr1t3yu9egn5t8fsmsp0k4 FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Eq1s4xQ3V7s4i8S35waQsy2Hz2AALCYFitCGck78bRFUX9rph0mJM1LLydYoHfY

