# =========================
# Database
# =========================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/garagecare}
spring.datasource.username=${DB_USERNAME:garagecare}
spring.datasource.password=${DB_PASSWORD:garagecare}


# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true


# =========================
# Logging
# =========================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE